package pojo;
// Generated Aug 24, 2019 5:34:03 PM by Hibernate Tools 4.3.1



/**
 * ClassObjectStudent generated by hbm2java
 */
public class ClassObjectStudent  implements java.io.Serializable {


     private int id;
     private String classCode;
     private String objectCode;
     private String studentCode;

    public ClassObjectStudent() {
    }

    public ClassObjectStudent(int id, String classCode, String objectCode, String studentCode) {
       this.id = id;
       this.classCode = classCode;
       this.objectCode = objectCode;
       this.studentCode = studentCode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getClassCode() {
        return this.classCode;
    }
    
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }
    public String getObjectCode() {
        return this.objectCode;
    }
    
    public void setObjectCode(String objectCode) {
        this.objectCode = objectCode;
    }
    public String getStudentCode() {
        return this.studentCode;
    }
    
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }




}


