package pojo;
// Generated Aug 25, 2019 11:51:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ClassObjectStudent generated by hbm2java
 */
public class ClassObjectStudent  implements java.io.Serializable {


     private int id;
     private String classCode;
     private String objectCode;
     private String studentCode;
     private BigDecimal mark1;
     private BigDecimal mark2;
     private BigDecimal mark3;
     private BigDecimal mark4;

    public ClassObjectStudent() {
    }

	
    public ClassObjectStudent(int id, String classCode, String objectCode, String studentCode) {
        this.id = id;
        this.classCode = classCode;
        this.objectCode = objectCode;
        this.studentCode = studentCode;
    }
    public ClassObjectStudent(int id, String classCode, String objectCode, String studentCode, BigDecimal mark1, BigDecimal mark2, BigDecimal mark3, BigDecimal mark4) {
       this.id = id;
       this.classCode = classCode;
       this.objectCode = objectCode;
       this.studentCode = studentCode;
       this.mark1 = mark1;
       this.mark2 = mark2;
       this.mark3 = mark3;
       this.mark4 = mark4;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getClassCode() {
        return this.classCode;
    }
    
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }
    public String getObjectCode() {
        return this.objectCode;
    }
    
    public void setObjectCode(String objectCode) {
        this.objectCode = objectCode;
    }
    public String getStudentCode() {
        return this.studentCode;
    }
    
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }
    public BigDecimal getMark1() {
        return this.mark1;
    }
    
    public void setMark1(BigDecimal mark1) {
        this.mark1 = mark1;
    }
    public BigDecimal getMark2() {
        return this.mark2;
    }
    
    public void setMark2(BigDecimal mark2) {
        this.mark2 = mark2;
    }
    public BigDecimal getMark3() {
        return this.mark3;
    }
    
    public void setMark3(BigDecimal mark3) {
        this.mark3 = mark3;
    }
    public BigDecimal getMark4() {
        return this.mark4;
    }
    
    public void setMark4(BigDecimal mark4) {
        this.mark4 = mark4;
    }




}


