package pojo;
// Generated Aug 25, 2019 1:13:02 PM by Hibernate Tools 4.3.1



/**
 * Class generated by hbm2java
 */
public class Class  implements java.io.Serializable {


     private String code;
     private String name;

    public Class() {
    }

	
    public Class(String code) {
        this.code = code;
    }
    public Class(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


