package pojo;
// Generated Aug 25, 2019 10:05:30 AM by Hibernate Tools 4.3.1



/**
 * Object generated by hbm2java
 */
public class Object  implements java.io.Serializable {


     private String code;
     private String name;
     private String room;

    public Object() {
    }

	
    public Object(String code) {
        this.code = code;
    }
    public Object(String code, String name, String room) {
       this.code = code;
       this.name = name;
       this.room = room;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }




}


