package pojo;
// Generated Aug 25, 2019 9:30:34 AM by Hibernate Tools 4.3.1



/**
 * RemarkDetail generated by hbm2java
 */
public class RemarkDetail  implements java.io.Serializable {


     private int id;
     private String studentCode;
     private String objectCode;
     private int remarkPoint;
     private short remarkExpect;
     private String reason;

    public RemarkDetail() {
    }

    public RemarkDetail(int id, String studentCode, String objectCode, int remarkPoint, short remarkExpect, String reason) {
       this.id = id;
       this.studentCode = studentCode;
       this.objectCode = objectCode;
       this.remarkPoint = remarkPoint;
       this.remarkExpect = remarkExpect;
       this.reason = reason;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStudentCode() {
        return this.studentCode;
    }
    
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }
    public String getObjectCode() {
        return this.objectCode;
    }
    
    public void setObjectCode(String objectCode) {
        this.objectCode = objectCode;
    }
    public int getRemarkPoint() {
        return this.remarkPoint;
    }
    
    public void setRemarkPoint(int remarkPoint) {
        this.remarkPoint = remarkPoint;
    }
    public short getRemarkExpect() {
        return this.remarkExpect;
    }
    
    public void setRemarkExpect(short remarkExpect) {
        this.remarkExpect = remarkExpect;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


