package pojo;
// Generated Aug 25, 2019 1:13:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * RemarkDetail generated by hbm2java
 */
public class RemarkDetail  implements java.io.Serializable {


     private int id;
     private String studentCode;
     private String objectCode;
     private int remarkPoint;
     private BigDecimal remarkExpect;
     private String reason;
     private Date createTime;
     private BigDecimal remarkActual;
     private Integer status;

    public RemarkDetail() {
    }

	
    public RemarkDetail(int id, String studentCode, String objectCode, int remarkPoint, BigDecimal remarkExpect, String reason) {
        this.id = id;
        this.studentCode = studentCode;
        this.objectCode = objectCode;
        this.remarkPoint = remarkPoint;
        this.remarkExpect = remarkExpect;
        this.reason = reason;
    }
    public RemarkDetail(int id, String studentCode, String objectCode, int remarkPoint, BigDecimal remarkExpect, String reason, Date createTime, BigDecimal remarkActual, Integer status) {
       this.id = id;
       this.studentCode = studentCode;
       this.objectCode = objectCode;
       this.remarkPoint = remarkPoint;
       this.remarkExpect = remarkExpect;
       this.reason = reason;
       this.createTime = createTime;
       this.remarkActual = remarkActual;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStudentCode() {
        return this.studentCode;
    }
    
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }
    public String getObjectCode() {
        return this.objectCode;
    }
    
    public void setObjectCode(String objectCode) {
        this.objectCode = objectCode;
    }
    public int getRemarkPoint() {
        return this.remarkPoint;
    }
    
    public void setRemarkPoint(int remarkPoint) {
        this.remarkPoint = remarkPoint;
    }
    public BigDecimal getRemarkExpect() {
        return this.remarkExpect;
    }
    
    public void setRemarkExpect(BigDecimal remarkExpect) {
        this.remarkExpect = remarkExpect;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public BigDecimal getRemarkActual() {
        return this.remarkActual;
    }
    
    public void setRemarkActual(BigDecimal remarkActual) {
        this.remarkActual = remarkActual;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


